[package]
org = "narib"
name = "client"
version = "0.1.0"
distribution = "2201.7.2"

[build-options]
observabilityIncluded = true


host = "mongodb://localhost:27017"
port = 27017
database = "PerfomanceManagement"